[env:xiao_esp32-s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -D CONFIG_BT_NIMBLE_EXT_ADV=0
    -D CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=5120
    -D BOARD_HAS_PSRAM
    -D CONFIG_ARDUINO_LOO_STACK_SIZE=16384
    -O3
    -Wall
    -Wextra
    -Isrc

lib_deps = 
    h2zero/NimBLE-Arduino@^2.1.0
    bblanchon/ArduinoJson@^7.2.0
    adafruit/Adafruit NeoPixel

board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv

upload_speed = 115200
board_build.f_cpu = 240000000L
